// Helper to get accent color classes dynamically
export const getAccentClasses = (accentColor: string) => {
  const colorMap = {
    orange: {
      bg: 'bg-orange-500',
      bgHover: 'hover:bg-orange-600',
      bgLight: 'bg-orange-50',
      bgLightHover: 'hover:bg-orange-100',
      text: 'text-orange-600',
      textHover: 'hover:text-orange-700',
      border: 'border-orange-500',
      borderHover: 'hover:border-orange-600',
      ring: 'ring-orange-500',
      ringFocus: 'focus:ring-orange-500',
      gradient: 'from-orange-500 to-orange-600',
      gradientDark: 'dark:from-orange-400 dark:to-orange-500',
      badge: 'bg-orange-100 text-orange-700',
      badgeDark: 'dark:bg-orange-900/30 dark:text-orange-300',
      active: 'bg-orange-50 text-orange-600 border-r-4 border-orange-500',
      activeDark: 'dark:bg-orange-900/30 dark:text-orange-400 dark:border-orange-400',
    },
    blue: {
      bg: 'bg-blue-500',
      bgHover: 'hover:bg-blue-600',
      bgLight: 'bg-blue-50',
      bgLightHover: 'hover:bg-blue-100',
      text: 'text-blue-600',
      textHover: 'hover:text-blue-700',
      border: 'border-blue-500',
      borderHover: 'hover:border-blue-600',
      ring: 'ring-blue-500',
      ringFocus: 'focus:ring-blue-500',
      gradient: 'from-blue-500 to-blue-600',
      gradientDark: 'dark:from-blue-400 dark:to-blue-500',
      badge: 'bg-blue-100 text-blue-700',
      badgeDark: 'dark:bg-blue-900/30 dark:text-blue-300',
      active: 'bg-blue-50 text-blue-600 border-r-4 border-blue-500',
      activeDark: 'dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-400',
    },
    green: {
      bg: 'bg-green-500',
      bgHover: 'hover:bg-green-600',
      bgLight: 'bg-green-50',
      bgLightHover: 'hover:bg-green-100',
      text: 'text-green-600',
      textHover: 'hover:text-green-700',
      border: 'border-green-500',
      borderHover: 'hover:border-green-600',
      ring: 'ring-green-500',
      ringFocus: 'focus:ring-green-500',
      gradient: 'from-green-500 to-green-600',
      gradientDark: 'dark:from-green-400 dark:to-green-500',
      badge: 'bg-green-100 text-green-700',
      badgeDark: 'dark:bg-green-900/30 dark:text-green-300',
      active: 'bg-green-50 text-green-600 border-r-4 border-green-500',
      activeDark: 'dark:bg-green-900/30 dark:text-green-400 dark:border-green-400',
    },
    purple: {
      bg: 'bg-purple-500',
      bgHover: 'hover:bg-purple-600',
      bgLight: 'bg-purple-50',
      bgLightHover: 'hover:bg-purple-100',
      text: 'text-purple-600',
      textHover: 'hover:text-purple-700',
      border: 'border-purple-500',
      borderHover: 'hover:border-purple-600',
      ring: 'ring-purple-500',
      ringFocus: 'focus:ring-purple-500',
      gradient: 'from-purple-500 to-purple-600',
      gradientDark: 'dark:from-purple-400 dark:to-purple-500',
      badge: 'bg-purple-100 text-purple-700',
      badgeDark: 'dark:bg-purple-900/30 dark:text-purple-300',
      active: 'bg-purple-50 text-purple-600 border-r-4 border-purple-500',
      activeDark: 'dark:bg-purple-900/30 dark:text-purple-400 dark:border-purple-400',
    },
    pink: {
      bg: 'bg-pink-500',
      bgHover: 'hover:bg-pink-600',
      bgLight: 'bg-pink-50',
      bgLightHover: 'hover:bg-pink-100',
      text: 'text-pink-600',
      textHover: 'hover:text-pink-700',
      border: 'border-pink-500',
      borderHover: 'hover:border-pink-600',
      ring: 'ring-pink-500',
      ringFocus: 'focus:ring-pink-500',
      gradient: 'from-pink-500 to-pink-600',
      gradientDark: 'dark:from-pink-400 dark:to-pink-500',
      badge: 'bg-pink-100 text-pink-700',
      badgeDark: 'dark:bg-pink-900/30 dark:text-pink-300',
      active: 'bg-pink-50 text-pink-600 border-r-4 border-pink-500',
      activeDark: 'dark:bg-pink-900/30 dark:text-pink-400 dark:border-pink-400',
    },
    teal: {
      bg: 'bg-teal-500',
      bgHover: 'hover:bg-teal-600',
      bgLight: 'bg-teal-50',
      bgLightHover: 'hover:bg-teal-100',
      text: 'text-teal-600',
      textHover: 'hover:text-teal-700',
      border: 'border-teal-500',
      borderHover: 'hover:border-teal-600',
      ring: 'ring-teal-500',
      ringFocus: 'focus:ring-teal-500',
      gradient: 'from-teal-500 to-teal-600',
      gradientDark: 'dark:from-teal-400 dark:to-teal-500',
      badge: 'bg-teal-100 text-teal-700',
      badgeDark: 'dark:bg-teal-900/30 dark:text-teal-300',
      active: 'bg-teal-50 text-teal-600 border-r-4 border-teal-500',
      activeDark: 'dark:bg-teal-900/30 dark:text-teal-400 dark:border-teal-400',
    },
  };
  
  return colorMap[accentColor as keyof typeof colorMap] || colorMap.orange;
};